-- ═══════════════════════════════════════════════════════════════
-- CAREBIURO WINDYKACJA - Szybka migracja bazy danych
-- ═══════════════════════════════════════════════════════════════
-- Data: 2025-10-07
-- Wersja: 1.3.0
--
-- INSTRUKCJA:
-- 1. Otwórz Supabase SQL Editor
-- 2. Skopiuj i wklej całą zawartość tego pliku
-- 3. Kliknij "Run"
--
-- Bezpieczne - można uruchomić wielokrotnie (sprawdza czy istnieje)
-- ═══════════════════════════════════════════════════════════════

-- ┌─────────────────────────────────────────────────────────────┐
-- │ KROK 1: Dodaj kolumnę list_polecony do tabeli clients      │
-- └─────────────────────────────────────────────────────────────┘

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_name = 'clients'
    AND column_name = 'list_polecony'
  ) THEN
    ALTER TABLE clients ADD COLUMN list_polecony BOOLEAN DEFAULT false;
    RAISE NOTICE '✓ Kolumna list_polecony została dodana';
  ELSE
    RAISE NOTICE '→ Kolumna list_polecony już istnieje';
  END IF;
END $$;

-- Index dla list_polecony
CREATE INDEX IF NOT EXISTS idx_clients_list_polecony
ON clients(list_polecony)
WHERE list_polecony = true;


-- ┌─────────────────────────────────────────────────────────────┐
-- │ KROK 2: Utwórz tabelę message_history                      │
-- └─────────────────────────────────────────────────────────────┘

CREATE TABLE IF NOT EXISTS message_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id BIGINT REFERENCES clients(id) ON DELETE CASCADE,
  invoice_id BIGINT REFERENCES invoices(id) ON DELETE CASCADE,
  invoice_number TEXT NOT NULL,
  client_name TEXT NOT NULL,

  -- Typ wiadomości i poziom
  message_type TEXT NOT NULL CHECK (message_type IN ('email', 'sms', 'whatsapp')),
  level INTEGER NOT NULL CHECK (level IN (1, 2, 3)),

  -- Status wysyłki
  status TEXT NOT NULL CHECK (status IN ('sent', 'failed')),
  error_message TEXT,

  -- Metadane
  sent_at TIMESTAMP DEFAULT now(),
  sent_by TEXT DEFAULT 'system', -- 'system' dla auto-send, 'manual' dla ręcznych
  is_auto_initial BOOLEAN DEFAULT false, -- true dla E1/S1/W1 z auto-send-initial

  -- Kopia danych faktury (na wypadek usunięcia)
  invoice_total NUMERIC,
  invoice_currency TEXT
);


-- ┌─────────────────────────────────────────────────────────────┐
-- │ KROK 3: Dodaj indeksy dla message_history                  │
-- └─────────────────────────────────────────────────────────────┘

CREATE INDEX IF NOT EXISTS idx_message_history_client_id
ON message_history(client_id);

CREATE INDEX IF NOT EXISTS idx_message_history_invoice_id
ON message_history(invoice_id);

CREATE INDEX IF NOT EXISTS idx_message_history_sent_at
ON message_history(sent_at DESC);

CREATE INDEX IF NOT EXISTS idx_message_history_message_type
ON message_history(message_type);

CREATE INDEX IF NOT EXISTS idx_message_history_level
ON message_history(level);

CREATE INDEX IF NOT EXISTS idx_message_history_is_auto_initial
ON message_history(is_auto_initial)
WHERE is_auto_initial = true;


-- ┌─────────────────────────────────────────────────────────────┐
-- │ WERYFIKACJA                                                 │
-- └─────────────────────────────────────────────────────────────┘

DO $$
DECLARE
  list_polecony_exists BOOLEAN;
  message_history_exists BOOLEAN;
BEGIN
  -- Sprawdź list_polecony
  SELECT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'clients' AND column_name = 'list_polecony'
  ) INTO list_polecony_exists;

  -- Sprawdź message_history
  SELECT EXISTS (
    SELECT 1 FROM information_schema.tables
    WHERE table_name = 'message_history'
  ) INTO message_history_exists;

  -- Wyświetl podsumowanie
  RAISE NOTICE '';
  RAISE NOTICE '═══════════════════════════════════════════════';
  RAISE NOTICE '  MIGRACJA ZAKOŃCZONA';
  RAISE NOTICE '═══════════════════════════════════════════════';
  RAISE NOTICE '';

  IF list_polecony_exists THEN
    RAISE NOTICE '✓ Kolumna clients.list_polecony: OK';
  ELSE
    RAISE WARNING '✗ Kolumna clients.list_polecony: BRAK';
  END IF;

  IF message_history_exists THEN
    RAISE NOTICE '✓ Tabela message_history: OK';
  ELSE
    RAISE WARNING '✗ Tabela message_history: BRAK';
  END IF;

  RAISE NOTICE '';
  RAISE NOTICE 'Możesz teraz używać:';
  RAISE NOTICE '  - Zakładki "Historia" w aplikacji';
  RAISE NOTICE '  - Automatycznego logowania wiadomości';
  RAISE NOTICE '  - API /api/historia';
  RAISE NOTICE '';
END $$;
