-- Fiscal Sync Database Schema
-- Run this in Supabase SQL Editor

-- Tabela klientów
CREATE TABLE IF NOT EXISTS clients (
  id BIGINT PRIMARY KEY,
  name TEXT,
  first_name TEXT, -- Imię klienta z Fakturowni
  last_name TEXT, -- Nazwisko klienta z Fakturowni
  email TEXT,
  phone TEXT,
  total_unpaid NUMERIC,
  note TEXT, -- Komentarz z Fakturowni (zawiera [WINDYKACJA] i [LIST_POLECONY])
  list_polecony BOOLEAN DEFAULT false, -- Flaga oznaczająca klienta do listu poleconego
  updated_at TIMESTAMP DEFAULT now()
);

-- Tabela faktur
CREATE TABLE IF NOT EXISTS invoices (
  id BIGINT PRIMARY KEY,
  client_id BIGINT REFERENCES clients(id) ON DELETE CASCADE,
  number TEXT,
  total NUMERIC,
  status TEXT,
  internal_note TEXT, -- Komentarz wewnętrzny z Fakturowni (zawiera [FISCAL_SYNC])
  email_status TEXT,
  sent_time TIMESTAMP,
  updated_at TIMESTAMP DEFAULT now(),

  -- Dodatkowe pola potrzebne do PDF/Excel
  issue_date TIMESTAMP,
  sell_date TIMESTAMP,
  payment_to TIMESTAMP,
  paid_date TIMESTAMP,
  created_at TIMESTAMP,

  -- Dane finansowe
  price_net NUMERIC,
  price_tax NUMERIC,
  paid NUMERIC,
  outstanding NUMERIC, -- Saldo do zapłaty (total - paid), może być NULL jeśli paid NULL
  currency TEXT,
  payment_type TEXT,

  -- Dane nabywcy (z faktury)
  buyer_name TEXT,
  buyer_email TEXT,
  buyer_phone TEXT,
  buyer_tax_no TEXT,
  buyer_street TEXT,
  buyer_city TEXT,
  buyer_post_code TEXT,
  buyer_country TEXT,

  -- Metadane dokumentu
  kind TEXT,
  description TEXT,
  place TEXT,
  view_url TEXT,
  payment_url TEXT,
  overdue BOOLEAN,
  print_time TIMESTAMP,

  -- Flagi optymalizacji i list polecony
  has_third_reminder BOOLEAN DEFAULT false, -- true jeśli EMAIL_3/SMS_3/WHATSAPP_3 = true w [FISCAL_SYNC]
  list_polecony BOOLEAN DEFAULT false, -- Faktura ma wysłany list polecony
  list_polecony_sent_date DATE, -- Data wysłania listu poleconego
  list_polecony_ignored BOOLEAN DEFAULT false, -- Faktura zignorowana (nie wysyłać do Kaczmarski)
  list_polecony_ignored_date TIMESTAMP -- Data zignorowania faktury
);

-- Tabela historii komentarzy
CREATE TABLE IF NOT EXISTS invoice_comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  invoice_id BIGINT REFERENCES invoices(id) ON DELETE CASCADE,
  body TEXT,
  created_at TIMESTAMP DEFAULT now(),
  source TEXT CHECK (source IN ('fakturownia','local'))
);

-- Tabela historii wysyłek (email, SMS, WhatsApp)
CREATE TABLE IF NOT EXISTS message_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id BIGINT REFERENCES clients(id) ON DELETE CASCADE,
  invoice_id BIGINT REFERENCES invoices(id) ON DELETE CASCADE,
  invoice_number TEXT NOT NULL,
  client_name TEXT NOT NULL,

  -- Typ wiadomości i poziom
  message_type TEXT NOT NULL CHECK (message_type IN ('email', 'sms', 'whatsapp')),
  level INTEGER NOT NULL CHECK (level IN (1, 2, 3)),

  -- Status wysyłki
  status TEXT NOT NULL CHECK (status IN ('sent', 'failed')),
  error_message TEXT,

  -- Metadane
  sent_at TIMESTAMPTZ DEFAULT now(),
  sent_by TEXT DEFAULT 'system', -- 'system' dla auto-send, 'manual' dla ręcznych
  is_auto_initial BOOLEAN DEFAULT false, -- true dla E1/S1/W1 z auto-send-initial

  -- Kopia danych faktury (na wypadek usunięcia)
  invoice_total NUMERIC,
  invoice_currency TEXT
);

-- Indeksy dla wydajności
CREATE INDEX IF NOT EXISTS idx_invoices_client_id ON invoices(client_id);
CREATE INDEX IF NOT EXISTS idx_invoices_status ON invoices(status);
CREATE INDEX IF NOT EXISTS idx_invoice_comments_invoice_id ON invoice_comments(invoice_id);
CREATE INDEX IF NOT EXISTS idx_invoices_updated_at ON invoices(updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_clients_updated_at ON clients(updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_clients_list_polecony ON clients(list_polecony) WHERE list_polecony = true;
CREATE INDEX IF NOT EXISTS idx_invoices_has_third_reminder ON invoices(has_third_reminder) WHERE has_third_reminder = true;

-- Indeksy dla message_history
CREATE INDEX IF NOT EXISTS idx_message_history_client_id ON message_history(client_id);
CREATE INDEX IF NOT EXISTS idx_message_history_invoice_id ON message_history(invoice_id);
CREATE INDEX IF NOT EXISTS idx_message_history_sent_at ON message_history(sent_at DESC);
CREATE INDEX IF NOT EXISTS idx_message_history_message_type ON message_history(message_type);
CREATE INDEX IF NOT EXISTS idx_message_history_level ON message_history(level);
CREATE INDEX IF NOT EXISTS idx_message_history_is_auto_initial ON message_history(is_auto_initial) WHERE is_auto_initial = true;

-- RLS (Row Level Security) - włącz później jeśli potrzebne
-- ALTER TABLE clients ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE invoices ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE invoice_comments ENABLE ROW LEVEL SECURITY;
