-- Migration: Add message_history table
-- Date: 2025-10-07

-- Create message_history table if it doesn't exist
CREATE TABLE IF NOT EXISTS message_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id BIGINT REFERENCES clients(id) ON DELETE CASCADE,
  invoice_id BIGINT REFERENCES invoices(id) ON DELETE CASCADE,
  invoice_number TEXT NOT NULL,
  client_name TEXT NOT NULL,

  -- Typ wiadomości i poziom
  message_type TEXT NOT NULL CHECK (message_type IN ('email', 'sms', 'whatsapp')),
  level INTEGER NOT NULL CHECK (level IN (1, 2, 3)),

  -- Status wysyłki
  status TEXT NOT NULL CHECK (status IN ('sent', 'failed')),
  error_message TEXT,

  -- Metadane
  sent_at TIMESTAMP DEFAULT now(),
  sent_by TEXT DEFAULT 'system', -- 'system' dla auto-send, 'manual' dla ręcznych
  is_auto_initial BOOLEAN DEFAULT false, -- true dla E1/S1/W1 z auto-send-initial

  -- Kopia danych faktury (na wypadek usunięcia)
  invoice_total NUMERIC,
  invoice_currency TEXT
);

-- Create indexes for message_history
CREATE INDEX IF NOT EXISTS idx_message_history_client_id ON message_history(client_id);
CREATE INDEX IF NOT EXISTS idx_message_history_invoice_id ON message_history(invoice_id);
CREATE INDEX IF NOT EXISTS idx_message_history_sent_at ON message_history(sent_at DESC);
CREATE INDEX IF NOT EXISTS idx_message_history_message_type ON message_history(message_type);
CREATE INDEX IF NOT EXISTS idx_message_history_level ON message_history(level);
CREATE INDEX IF NOT EXISTS idx_message_history_is_auto_initial ON message_history(is_auto_initial) WHERE is_auto_initial = true;
